---
deployment:
  tasks:
    - export DEPLOYPATH=/home3/glmflqmy/public_html/accelerate/staging/1337/
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp style.css $DEPLOYPATH
    - /bin/cp -R images $DEPLOYPATH
    - /bin/cp -R wp-content $DEPLOYPATH